import { assert, describe, setupRitewayBun, test } from 'riteway/bun';
import { readdir } from 'node:fs/promises';

setupRitewayBun();

const migrations = new URL('../migrations/', import.meta.url).pathname;
const repository = new URL('../../../', import.meta.url).pathname;

describe('the migration history (ISSUE-6)', () => {
  test('starts from exactly one baseline, and every folder uses the drizzle-kit 1.0 layout', async () => {
    const entries = (await readdir(migrations, { withFileTypes: true }))
      .map((entry) => ({ name: entry.name, folder: entry.isDirectory() }))
      .sort((a, b) => a.name.localeCompare(b.name));
    const layouts = await Promise.all(
      entries.map(async ({ name, folder }) => ({
        folder,
        named: /^\d{14}_[a-z0-9_]+$/.test(name),
        files: folder ? (await readdir(`${migrations}${name}`)).sort() : [],
      })),
    );
    assert({
      given: 'packages/db/migrations',
      should:
        'open with one <14-digit timestamp>_baseline folder, hold no other baseline and no legacy meta/ journal, and give every folder only migration.sql and snapshot.json',
      actual: {
        first: /^\d{14}_baseline$/.test(entries[0]?.name ?? ''),
        baselines: entries.filter(({ name }) => name.endsWith('_baseline'))
          .length,
        layouts,
      },
      expected: {
        first: true,
        baselines: 1,
        layouts: entries.map(() => ({
          folder: true,
          named: true,
          files: ['migration.sql', 'snapshot.json'],
        })),
      },
    });
  });

  test('is sanctioned by one live baseline entry, with the inert ADR 0023 entry gone', async () => {
    const registry = (await Bun.file(
      `${repository}policy/migration-baselines.json`,
    ).json()) as { baselines: ReadonlyArray<{ adr: string }> };
    assert({
      given: 'policy/migration-baselines.json',
      should: 'hold only the ADR 0038 sanction for this squash',
      actual: registry.baselines.map(({ adr }) => adr),
      expected: ['docs/decisions/0038-drizzle-1-baseline.md'],
    });
  });

  test('is generated by the Drizzle 1.0 toolchain', async () => {
    const manifest = (await Bun.file(
      new URL('../package.json', import.meta.url).pathname,
    ).json()) as {
      dependencies: Record<string, string>;
      devDependencies: Record<string, string>;
    };
    assert({
      given: "@offense-demo/db's manifest",
      should: 'pin drizzle-orm and drizzle-kit to the same exact 1.0 release',
      actual: {
        orm: manifest.dependencies['drizzle-orm'],
        kit: manifest.devDependencies['drizzle-kit'],
      },
      expected: { orm: '1.0.0-rc.4', kit: '1.0.0-rc.4' },
    });
  });

  test('adds projects in exactly one forward migration after the baseline (PROJ-1.1)', async () => {
    const folders = (await readdir(migrations)).sort();
    const creators = (
      await Promise.all(
        folders.map(async (folder) => ({
          folder,
          sql: await Bun.file(`${migrations}${folder}/migration.sql`).text(),
        })),
      )
    )
      .filter(({ sql }) => /create table "projects"/i.test(sql))
      .map(({ folder }) => folders.indexOf(folder));
    assert({
      given: 'every committed migration',
      should:
        'create the projects table in exactly one folder, a forward migration after the baseline',
      actual: { count: creators.length, afterBaseline: creators[0]! > 0 },
      expected: { count: 1, afterBaseline: true },
    });
  });
});
